name = "chess_glm"
version = "1.0.0"
links = [
    { title = "Mist", href = "https://github.com/rawhat/mist" },
    { title = "Mist Docs", href = "https://hexdocs.pm/mist/" },
    { title = "html-dsl", href = "https://github.com/Qinbeans/html-dsl" },
    { title = "html-dsl Docs", href = "https://qinbeans.github.io/html-dsl/" }
]

repository = { type = "github", user = "Qinbeans", repo = "chess_glm" }

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/. 

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
mist = "~> 1.0"
gleam_erlang = "~> 0.25"
gleam_http = "~> 3.6"
gleam_otp = "~> 0.10"
html_dsl = { path = "dependencies/html-dsl" }
gleam_httpc = "~> 2.2"

[dev-dependencies]
gleeunit = "~> 1.0"